services:
  php:
    build:
      context: ./docker/services/php
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=8.3
    container_name: astecly_php
    restart: unless-stopped
    working_dir: /var/www
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5173:5173" 
    volumes:
      - ./app:/var/www
      - /mnt/data/astecly/storage:/var/www/storage/app/public
      - php-socket:/var/run/php-fpm
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/services/nginx
      dockerfile: nginx.dockerfile
    container_name: astecly_nginx
    restart: unless-stopped
    working_dir: /var/www
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./app:/var/www
      - /mnt/data/astecly/storage:/var/www/storage/app/public
      - php-socket:/var/run/php-fpm
    ports:
      - '80:80'
    depends_on:
      - php
    networks:
      - app-network

  database:
    image: mariadb:11.4
    container_name: astecly_db
    restart: unless-stopped
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - '3306:3306'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: astecly_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./docker/volumes/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  php-socket: